version: "3.7"

services:
  backend:
    image: dimmaryanto93/udemy-springboot-app:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: db_devops
      DATABASE_USER: bagas
      DATABASE_PASSWORD: 846452
      SERVER_PORT: 8080 
    depends_on:
      - db

  db:
    image: postgres:14.2
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: db_devops
      POSTGRES_USER: bagas
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  frontend:
    image: dimmaryanto93/udemy-angular-app:latest
    ports:
      - "80:80"
    environment:
      APPLICATION_PORT: 80
      NGINX_ROOT_DOCUMENT: /var/www/html
      BACKEND_HOST: backend
      BACKEND_PORT: 8080
      BACKEND_CONTEXT_PATH: /
    depends_on:
      - backend
